name: Go

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: backend/go.sum

      - name: Install dependencies
        run: go get backend/.
 
      - name: Test with the Go CLI
        run: go test -v backend/...
