name: Go

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/go.yaml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: backend/go.sum

      - name: Install dependencies
        run: go get .
        working-directory: ./backend
 
      - name: Test
        run: go test -v ./...
        working-directory: ./backend

      # - name: Build
      #   run: go build -v ./...
      #   working-directory: ./backend
